language: csharp
dist: trusty
mono: none
dotnet: 2.0.0
install:
- dotnet restore
script:
- dotnet test test/Pidget.Client.Test/Pidget.Client.Test.csproj
- dotnet test test/Pidget.AspNet.Test/Pidget.AspNet.Test.csproj
